//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolivanovZachet.DataBaesF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocenka
    {
        public int Id { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdDesciplina { get; set; }
        public Nullable<int> Ocen { get; set; }
    
        public virtual Desciplina Desciplina { get; set; }
        public virtual Student Student { get; set; }
    }
}
