//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolivanovZachet.DataBaesF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Ocenka = new HashSet<Ocenka>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> IdSpec { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
        public string FormaOb { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocenka> Ocenka { get; set; }
        public virtual Spec Spec { get; set; }
    }
}
